/*
 * Mollie Burkle
 * Project Euler
 * Problem 2 - Even Fibonacci numbers
	Each new term in the Fibonacci sequence is generated by adding the previous 
	two terms. By starting with 1 and 2, the first 10 terms will be:
		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	Find the sum of the even-valued terms.
 */
public class Run {

	public static void main(String[] args) {
		int prev1 = 1;
		int prev2 = 2;
		int sums = 2;

		for (int i = 3; i < 4000000;) {
			prev1 = prev2;
			prev2 = i;
			i = (prev1 + prev2);
			if (i%2 == 0) {
				sums+= i;
			}
			
		}
		System.out.println(sums);
	}

}
